plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.1.38'
}

version = '1.21.0'
group = 'com.arlight.bosses'
base { archivesName = 'ArlightBosses' }
java.toolchain.languageVersion = JavaLanguageVersion.of(21)
repositories {
    mavenCentral()
    maven {
        name = 'GeckoLib'
        url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content { includeGroup 'software.bernie.geckolib' }
    }
}
dependencies {
    implementation 'net.neoforged:neoforge:21.1.235'
    implementation "software.bernie.geckolib:geckolib-neoforge-1.21.1:${geckolib_version}"
}
runs {
    configureEach { systemProperty 'forge.logging.console.level', 'debug'; modSource sourceSets.main }
    client { client() }
    server { server() }
}
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
tasks.withType(ProcessResources).configureEach {
    inputs.property 'version', project.version
    filesMatching('META-INF/neoforge.mods.toml') { expand version: project.version }
}
