modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="arlightbosses"
version="${version}"
displayName="ArlightBosses"
description='''Entidades y jefes personalizados para los minijuegos de Arlight.'''

[[dependencies.arlightbosses]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.arlightbosses]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.arlightbosses]]
modId="geckolib"
type="required"
versionRange="[4.9.2,5.0)"
ordering="AFTER"
side="BOTH"
